version: "3.9"

services:
  web:
    container_name: web
    build: './build/php'
    volumes:
      - ./app:/var/www/html/
    ports:
      - 80:80
      #- 443:443 TODO: Use TLS w\self-signed key
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    container_name: db
    build: './build/mariadb'
    env_file:
      - ./.env
    # ports:
     # - 3306:3306 # Expose db if needed

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    env_file:
      - ./.env